In [4]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Sample texts
texts = [
    "I love machine learning",
    "Deep learning is a subset of machine learning",
    "Natural language processing is a fascinating field"
]

# Initialize the tokenizer
tokenizer = Tokenizer(num_words=100)  # num_words limits the vocabulary size to the top 100 words

# Fit the tokenizer on the texts
tokenizer.fit_on_texts(texts)

# Print the word index
print("Word Index:\n", tokenizer.word_index)

# Convert texts to sequences
sequences = tokenizer.texts_to_sequences(texts)
print("Sequences:\n", sequences)

# Pad the sequences to ensure uniform length
padded_sequences = pad_sequences(sequences, padding='post')
print("Padded Sequences:\n", padded_sequences)

Word Index:
 {'learning': 1, 'machine': 2, 'is': 3, 'a': 4, 'i': 5, 'love': 6, 'deep': 7, 'subset': 8, 'of': 9, 'natural': 10, 'language': 11, 'processing': 12, 'fascinating': 13, 'field': 14}
Sequences:
 [[5, 6, 2, 1], [7, 1, 3, 4, 8, 9, 2, 1], [10, 11, 12, 3, 4, 13, 14]]
Padded Sequences:
 [[ 5  6  2  1  0  0  0  0]
 [ 7  1  3  4  8  9  2  1]
 [10 11 12  3  4 13 14  0]]
